language: python
dist: xenial

python:
  - 3.5

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install: pip install -e .

script:
  - flake8 ninjin
  - mypy ninjin
  - pytest
  - pip check

services:
  - postgresql
  - rabbitmq

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change